// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "puzzleocx.h"

/////////////////////////////////////////////////////////////////////////////
// CPuzzleOcx

IMPLEMENT_DYNCREATE(CPuzzleOcx, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CPuzzleOcx properties

long CPuzzleOcx::GetHintTime()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CPuzzleOcx::SetHintTime(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CPuzzleOcx operations

void CPuzzleOcx::GameStart()
{
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CPuzzleOcx::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
