#if !defined(AFX_PUZZLEOCX_H__94C7710F_61AE_11D5_874E_0050DA8BB346__INCLUDED_)
#define AFX_PUZZLEOCX_H__94C7710F_61AE_11D5_874E_0050DA8BB346__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPuzzleOcx wrapper class

class CPuzzleOcx : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPuzzleOcx)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9abf36a6, 0x6015, 0x11d5, { 0x87, 0x4e, 0x0, 0x50, 0xda, 0x8b, 0xb3, 0x46 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetHintTime();
	void SetHintTime(long);

// Operations
public:
	void GameStart();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PUZZLEOCX_H__94C7710F_61AE_11D5_874E_0050DA8BB346__INCLUDED_)
